### ISSUE TITLE
Simulation for initial work

### ISSUE THREAD

**Issue by hawesie** [g-gemignani/spatio-temporal-cues#1]
We will use MORSE: http://www.openrobots.org/morse/doc/stable/morse.html
1. Build the "2 desks" world as discussed:
   - MORSE tutorials: http://www.openrobots.org/morse/doc/stable/tutorials.html
   - Examples of simulations from https://github.com/strands-project/strands_morse
   - Some (perhaps additional) object meshes: https://github.com/strands-project/soma/tree/master/soma_objects/meshes
2. Create a metric map of the environment 
3. Create a SOMA object map: https://github.com/strands-project/soma

**Comment by hawesie** [comment]
I thought this might be better than email ;)

**Comment by g-gemignani** [comment]
Great, I'll start working on it! :)

**Comment by g-gemignani** [comment]
Task completed and pushed!
